# General configuration
run:
  project_name: "starvector-RL-eval"
  out_dir: "eval_results"
  report_to: wandb
  run_id: test-eval3
  log_images: false

# Model configuration
model:
  name: "starvector/starvector-8b-im2svg"   # Required: Model name for HF-based model
  from_checkpoint: false
  generation_engine: "vllm"
  task: im2svg
  torch_dtype: float16
  # image_processor: clip # is this needed?

# Dataset configuration
dataset:
  dataset_name: starvector/svg-stack  # Required: Name of the dataset to evaluate on
  config_name: null # in bigodcs set Image2SVG
  split: test
  batch_size: 8
  num_workers: 8
  im_size: 224
  num_samples: 500

# vllm https://docs.vllm.ai/en/v0.5.5/dev/sampling_params.html
# hf https://huggingface.co/docs/transformers/main_classes/text_generation
generation_params:
  # Text generation parameters
  max_length: 7933 # 8192 - (visual tokens)
  num_generations: 1
  min_length: 10
  num_beams: 1
  temperature: 0.5
  generation_sweep: false # Controls multi-temperature sampling, rank based sampling
    # num_generations_different_temp: 5
    # min_temperature: 0.0
    # max_temperature: 0.5
  num_captions: 1
  frequency_penalty: 0.0
  presence_penalty: 0.0
  repetition_penalty: 1.0
  top_p: 0.9
  logit_bias: 5 # if this is not false, the model will be biased to the svg_end_token_id
  min_p: 0.0
  top_k: -1
  stream: false


